var people = [
    {
        name: "Alexander van Wijk",
        username: "Alexander van Wijk",
        email: "",
        phone_number: "",
        creation: "",
        role_play: "",
        presence: "",
        bio: "",
        city: "",
        country: "",
        talents: "",
        specialization: "",
        photo: "images/people/Alexander van Wijk.jpg",
    },
    {
        name: "annemarijn",
        username: "annemarijn",
        email: "",
        phone_number: "",
        creation: "",
        role_play: "",
        presence: "",
        bio: "",
        city: "",
        country: "",
        talents: "",
        specialization: "",
        photo: "images/people/annemarijn.jpg",
    },
    {
        name: "Bradley",
        username: "Bradley",
        email: "",
        phone_number: "",
        creation: "",
        role_play: "",
        presence: "",
        bio: "",
        city: "",
        country: "",
        talents: "",
        specialization: "",
        photo: "images/people/Bradley.jpg",
    },
    {
        name: "Bram",
        username: "Bram or Kate",
        email: "merkobman@gmail.com",
        phone_number: "+31681100110",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "A cross-dressed bundle of energy ready for interaction. Moved to Rotterdam for the arts and stayed for the people. Making every situation a playful and educational experience. City's originally from the city of beverwijk. Now living in rotterdam after sampling the world.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "",
        photo: "images/people/bram.jpg",
    },
    {
        name: "Christo",
        username: "Christo",
        email: "christoklumper@hotmail.com",
        phone_number: "+31657650896",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "Levensgenieter en levensonderzoeker. Levenslang.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "Acting/Theater",
        photo: "images/people/christo.jpg",
    },
    {
        name: "Claudia",
        username: "Claudia Caldarone",
        email: "claudiacharl03@gmail.com",
        phone_number: "+393283967988",
        creation: "Yes",
        role_play: "Yes",
        presence: "Yes",
        bio: "None",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "I'm a dancer",
        specialization: "Mediation/Education, Performance/Dance",
        photo: "images/people/claudia.jpg",
    },
    {
        name: "Kirsten",
        username: "Kirsten",
        email: "kirsten_vanlienden@hotmail.com",
        phone_number: "+31637327476",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "Hoi, mijn naam is Kirsten en ik ben een bezig bijtje.  Recent afgestudeerd als ingenieur, maar ook gek op sport, muziek en theater en daarbij vol idealen om een bijdrage te leveren aan een betere wereld. Een wereld vol liefde voor elkaar en alles om ons heen.",
        city: "Delft",
        country: "The Netherlands",
        talents: "",
        specialization: "",
        photo: "images/people/kirsten.jpg",
    },
    {
        name: "Lisa Stroeve",
        username: "Lisa",
        email: "lisastroeve@hotmail.com",
        phone_number: "+31637283161",
        creation: "Maybe",
        role_play: "Yes",
        presence: "Maybe",
        bio: "in Heaven. on Earth.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "I am a Love Pirate and I make people feel better and act better by just being me",
        specialization: "Acting/Theater, Performance/Dance, Writing/Storytellings",
        photo: "images/people/lisa.jpg",
    },
    {
        name: "Garvan",
        username: "Garvan",
        email: "Garvancorr@gmail.com",
        phone_number: "+35383816123",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "I am an artist, an absurdist and an idealist. I am a loiterer, a collector and a video maker. I like to cycle my bike with no hands, and I think I'm pretty good at it. I like to do crossword puzzles and I watch youtube videos about geography. I am from Dublin, Ireland, I have been living in Rotterdam for 6 months.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "Photography/Film",
        photo: "images/people/garvan.jpg",
    },
    {
        name: "Giek",
        username: "Giek",
        email: "",
        phone_number: "",
        creation: "",
        role_play: "",
        presence: "",
        bio: "",
        city: "",
        country: "",
        talents: "",
        specialization: "",
        photo: "images/people/Giek.jpg",
    },
    {
        name: "Oyabradoh",
        username: "Oyabradoh",
        email: "oyabradoh.enodeh@gmail.com",
        phone_number: "+310644310354",
        creation: "Yes",
        role_play: "Yes",
        presence: "Yes",
        bio: "Afro European with a passion for Surfing. Living here and there since 35 years. When you think it is enough, just add a bit more.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "Photography/Film",
        photo: "images/people/oyabradoh.jpg",
    },
    {
        name: "Kat",
        username: "Kat",
        email: "",
        phone_number: "",
        creation: "",
        role_play: "",
        presence: "",
        bio: "",
        city: "",
        country: "",
        talents: "",
        specialization: "",
        photo: "images/people/Kat.jpg",
    },
    {
        name: "Lava",
        username: "Lava",
        email: "",
        phone_number: "",
        creation: "",
        role_play: "",
        presence: "",
        bio: "",
        city: "",
        country: "",
        talents: "",
        specialization: "",
        photo: "images/people/Lava.jpg",
    },
    {
        name: "Marloes",
        username: "Marloes",
        email: "marloesroeper@gmail.com",
        phone_number: "+31629346553",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "Daadkrachtig, gedreven, ongelofelijk grappig en lomp, aldus mijn huisgenoot.",
        city: "Utrecht",
        country: "The Netherlands",
        talents: "",
        specialization: "Visual/Conceptual art",
        photo: "images/people/marloes.jpg",
    },
    {
        name: "Joshua",
        username: "Joshua",
        email: "misterthies@gmail.com",
        phone_number: "+31624471956",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "My name is Joshua Thies and I host radio programmes like RAAR (Rotterdam Art And Radio). I can show you how to make podcasts and help you and your colleagues to listen deeply to your sonic environments.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "Visual/Conceptual art",
        photo: "images/people/joshua.jpg",
    },
    {
        name: "Marija",
        username: "Marija",
        email: "marija.ajdukovic@gmail.com",
        phone_number: "+31611485288",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "Mijn naam is Marija. Ik ben in Belgrado geboren, in een land dat niet meer bestaat. Ik woon nu in Rotterdam. Hier heb ik een stukje geluk gevonden. Hoop nog meer stukjes te vinden.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "",
        photo: "images/people/marija.jpg",
    },
    {
        name: "Juvy",
        username: "Juvy",
        email: "info@juvydesigns.nl",
        phone_number: "+31641900667",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "I’m just a creative mind trying to live his life to the max. Being a AfroCubano man, the world has show me so many beautiful things that whatever your doing or working trough life, it’s worth it.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "",
        photo: "images/people/juvy.jpg",
    },
    {
        name: "Linus",
        username: "Linus",
        email: "linusbondu@gmail.com",
        phone_number: "+32472555510",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "Artist, graphic designer, DJ, musician",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "Visual/Conceptual art",
        photo: "images/people/linus.jpg",
    },
    {
        name: "Lisa Meijer",
        username: "Lisa",
        email: "meliijer@gmail.com",
        phone_number: "+31629460615",
        creation: "Yes",
        role_play: "Yes",
        presence: "Yes",
        bio: "I'm an artist, researcher and cultural mediator in Rotterdam.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "I love to create concepts",
        specialization: "Mediation/Education, Visual/Conceptual art, Photography/Film",
        photo: "images/people/lisam.jpg",
    },
    
    {
        name: "Rawsht TWANA",
        username: "Rawsht",
        email: "rawsht.twana@gmail.com",
        phone_number: "None",
        creation: "Maybe",
        role_play: "No",
        presence: "Yes",
        bio: "Rawsht Twana is a photographer and archivist. He started taking photos in 2006 following in his father’s footsteps. In 2009, he started working as a photojournalist for Metrography - an independent photography agency based in Iraq - documenting social events through intimate and long-term projects in Iraqi Kurdistan. His images have been published in many international magazines and media outlets.",
        city: "Turin",
        country: "Italy",
        talents: "Yes, archivist",
        specialization: "Writing/Storytelling, Visual/Conceptual art, Photography/Film",
        photo: "images/people/rawsht.jpg",
    },
    {
        name: "Oana",
        username: "Oana",
        email: "hello@oanaclitan.com",
        phone_number: "+31686414707",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "Oana Clitan is an artist and designer and she likes to cook.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "Visual/Conceptual art",
        photo: "images/people/oana.jpg",
    },
    {
        name: "Tisa",
        username: "Tisa",
        email: "tisa.neza.herlec@gmail.com",
        phone_number: "+38641808214",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "I create imaginaries with my voice, text and images. I organize and enable, make radio, communicate and frequently perform in many different contexts, in diverse ensembles. I like plants and improvisation.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "Acting/Theater, Performance/Dance, Visual/Conceptual art",
        photo: "images/people/tisa.jpg",
    },
    {
        name: "Helen",
        username: "Helen",
        email: "helen_flanagan@live.co.uk",
        phone_number: "+31624828791",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "Helen is an artist based in Rotterdam. She works with moving image, installation, and performance.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "Performance/Dance, Photography/Film, Visual/Conceptual art",
        photo: "images/people/helen.jpg",
    },
    {
        name: "Rangoe",
        username: "Rangoe",
        email: "",
        phone_number: "",
        creation: "",
        role_play: "",
        presence: "",
        bio: "",
        city: "",
        country: "",
        talents: "",
        specialization: "",
        photo: "images/people/Rangoe.jpg",
    },
    {
        name: "Remy",
        username: "Remy",
        email: "info@remyleeflang.com",
        phone_number: "+31629453434",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "Biologe. Onderzoekt diergedrag en plantkunde.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "",
        photo: "images/people/remy.jpg",
    },
    {
        name: "Serdal",
        username: "Serdal",
        email: "sertdemirserdal@gmail.com",
        phone_number: "+31626241937",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "transcendental glasses of a philosophical utopian renaissance artist. in the world of prince and princesses, king and queens. there is non binary giant that collects en shares storys about new narraties of perceiving Art semiotic.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "Visual/Conceptual art",
        photo: "images/people/serdal.jpg",
    },
    {
        name: "Sophie",
        username: "Sophie",
        email: "sophie@vanrijsse.nl",
        phone_number: "+31611535909",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "Ik ben Vormgever, vrouw van Tomas, moeder van 2 meiden, en volger van Jezus. Ik ben zoekend naar liefde, het goede niet alleen voor mezelf maar juist ook de mensen om me heen. Ik kan me druk maken om de wereld en ik kan ook heel erg genieten van de wereld en heel erg blij zijn met mezelf.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "",
        photo: "images/people/sophie.jpg",
    },
    {
        name: "Thomas",
        username: "Thomas",
        email: "thomasjh11@hotmail.com",
        phone_number: "+31649792686",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "Zeeuw in Rotterdam who is into music, football and arts. Working as a freelance architect and graphic designer but will climb mountains for the next few years.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "",
        photo: "images/people/thomas.jpg",
    },
/*     {
        name: "Nola Bokun",
        username: "Nola",
        email: "nolabokun@gmail.com",
        phone_number: "+385919071744",
        creation: "Yes",
        role_play: "No",
        presence: "Yes",
        bio: "None",
        city: "Zagreb",
        country: "Croatia",
        talents: "Maybe I wouldn't call it a talent but I am a product designer interested in spatial design and scenography.",
        specialization: "Mediation/Education, Writing/Storytelling, Photography/Film",
        photo: "",
    }, */
    {
        name: "Peter van Waart",
        username: "Peter van Waart",
        email: "p.van.waart@hr.nl",
        phone_number: "+31624870988",
        creation: "No",
        role_play: "Maybe",
        presence: "Yes",
        bio: "Peter van Waart (Rotterdam University of Applied Sciences) is lecturer Digital Design and researcher Smart and Inclusive Society on participatory design methods for meaningful technology in the urban domain. Focusses on accounting for human values to design meaningful experiences. Coordinator of Smart & Social City network events and quadruple helix project developments. (Co-)Initiator and (co-)organiser of Rotterdam Open Data, Participatory City Making, OnsBlok, minor Urban Interaction Design, Global Service Jam Rotterdam, Rotterdam GovJam, International IoT Day Rotterdam, and Smart & Social Fest.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "Translating abstract goals into practical activities for people to experience.",
        specialization: "Mediation/Education",
        photo: "images/people/peter.jpg",
    },
    {
        name: "Ewan",
        username: "Ewan",
        email: "macbeth.ewan@gmail.com",
        phone_number: "+31616257569",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "Ewan is a Scottish artist based in Rotterdam. Working with filmmaking & photography his practice explores the (un)reality of power & propaganda.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "Photography/Film",
        photo: "images/people/ewan.jpg",
    }
];
