var people = [
    {
        name: "Bram",
        username: "Bram or Kate",
        email: "merkobman@gmail.com",
        phone_number: "+31681100110",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "A cross-dressed bundle of energy ready for interaction. Moved to Rotterdam for the arts and stayed for the people. Making every situation a playful and educational experience. City's originally from the city of beverwijk. Now living in rotterdam after sampling the world.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "",
        photo: "images/people/bram.jpg",
    },
    {
        name: "Christo",
        username: "Christo",
        email: "christoklumper@hotmail.com",
        phone_number: "+31657650896",
        creation: "Maybe",
        role_play: "Maybe",
        presence: "Maybe",
        bio: "Levensgenieter en levensonderzoeker. Levenslang.",
        city: "Rotterdam",
        country: "The Netherlands",
        talents: "",
        specialization: "Acting/Theater",
        photo: "images/people/christo.jpg",
    }
];