var people = [
    {
        name: "Garvan",
        invited: true,
        recall: "",
        status: "Done",
        from: "Dublin",
        lives_in: "Rotterdam",
        phone: "+35383816123",
        email: "garvancorr@gmail.com",
        description: "I am an artist, an absurdist and an idealist. I am a loiterer, a collector and a video maker. I like to cycle my bike with no hands, and I think I'm pretty good at it. I like to do crossword puzzles and I watch youtube videos about geography. I am from Dublin, Ireland, I have been living in Rotterdam for 6 months.",
        photo: "images/people/garvan.png",
    },
    {
        name: "Bram or Kate",
        invited: true,
        recall: "",
        status: "Done",
        from: "City Beverwijk",
        lives_in: "Rotterdam",
        phone: "+31681100110",
        email: "merkobman@gmail.com",
        description: "A cross-dressed bundle of energy ready for interaction. Moved to Rotterdam for the arts and stayed for the people. Making every situation a playful and educational experience.",
        photo: "images/people/bramkate.png",
    },
    {
        name: "Oana",
        invited: true,
        recall: "",
        status: "Done",
        from: "Belgium",
        lives_in: "Rotterdam",
        phone: "+32472555510",
        email: "linusbondu@gmail.com",
        description: "Artist, graphic designer, DJ, musician",
        photo: "images/people/linus.png",
    },
    {
        name: "Juvy",
        invited: true,
        recall: "",
        status: "Done",
        from: "Nihil",
        lives_in: "Rotterdam",
        phone: "+31641900667",
        email: "info@juvydesigns.nl",
        description: "I’m just a creative mind trying to live his life to the max. Being a AfroCubano man, the world has show me so many beautiful things that whatever your doing or working trough life, it’s worth it.",
        photo: "images/people/juvy.png",
    },
    {
        name: "Joshua",
        invited: true,
        recall: "",
        status: "Done",
        from: "",
        lives_in: "Rotterdam",
        phone: "+31624471956",
        email: "misterthies@gmail.com",
        description: "My name is Joshua Thies and I host radio programmes like RAAR (Rotterdam Art And Radio). I can show you how to make podcasts and help you and your colleagues to listen deeply to your sonic environments.",
        photo: "images/people/joshua.png",
    },
    {
        name: "Tisa",
        invited: false,
        recall: "",
        status: "Done",
        from: "Ljubljana, Slovenia",
        lives_in: "Rotterdam, Netherlands",
        phone: "+38641808214",
        email: "tisa.neza.herlec@gmail.com",
        description: "I create imaginaries with my voice, text and images. I organize and enable, make radio, communicate and frequently perform in many different contexts, in diverse ensembles. I like plants and improvisation.",
        photo: "images/people/tisa.png",
    },
    {
        name: "Thomas",
        invited: true,
        recall: "",
        status: "Done",
        from: "Oostburg, NL",
        lives_in: "Rotterdam, NL",
        phone: "+31649792686",
        email: "thomasjh11@hotmail.com",
        description: "Zeeuw in Rotterdam who is into music, football and arts. Working as a freelance architect and graphic designer but will climb mountains for the next few years.",
        photo: "images/people/thomas.png",
    },
    {
        name: "Marloes",
        invited: true,
        recall: "",
        status: "Done",
        from: "Texel",
        lives_in: "Utrecht",
        phone: "+33629346553",
        email: "marloesroeper@gmail.com",
        description: "Daadkrachtig, gedreven, ongelofelijk grappig en lomp, aldus mijn huisgenoot.",
        photo: "images/people/marloes.png",
    },
    {
        name: "Christo",
        invited: true,
        recall: "",
        status: "Done",
        from: "Berkel en Rodenrijs",
        lives_in: "Rotterdam",
        phone: "+31657650896",
        email: "christoklumper@hotmail.com",
        description: "Levensgenieter en levensonderzoeker. Levenslang.",
        photo: "images/people/christo.png",
    },
    {
        name: "DemDem BrrBrr (Enzo)",
        invited: true,
        recall: "",
        status: "Done",
        from: "Marseille",
        lives_in: "Rotterdam",
        phone: "Nihil",
        email: "accardien@gmail.com",
        description: "Artiste en Y",
        photo: "images/people/demdem.png",
    }
];